//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLABOUT
    {
        public int ID { get; set; }
        public string INFO { get; set; }
        public string EDUCATION { get; set; }
        public string EXPERIENCE { get; set; }
    }
}
