//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCONTACT
    {
        public byte ID { get; set; }
        public string TELEPHONE { get; set; }
        public string MAIL { get; set; }
        public string LOCATION { get; set; }
    }
}
